# =============================================
# EYN Plugin Configuration File
# =============================================

# Global Settings
settings:
  example-setting: true
  player-info:
    mask-ips: true
    show-exact-coords: false
  nametag:
    update-radius: 30
    log-changes: true
    prevent-bypass: true
  messaging:
    cooldown: 3
    socialspy-format: "&7[SPY] &d%sender% &8-> &d%receiver%&7: %message%"
    reply-prefix: "~"
    allow-message-toggling: true

# Discord Settings
discord:
  link: "https://discord.gg/example"  # Replace with your Discord invite link

# Heal Command Settings
heal:
  max_health: 20.0       # Default maximum health (double value)
  food_level: 20         # Food level to set (range 0-20)
  clear_fire: true       # Extinguish players when healed
  clear_effects: true    # Remove potion effects when healed

# Permission Overrides (if applicable)
permissions:
  override:
    eyn.nametag.others: "group.admin"
    eyn.vanish.others: "group.moderator"

# Cooldown Settings (in seconds)
cooldowns:
  clearchat: 3
  enchant: 10
  heal: 30

# Command Configurations
commands:
  msg:
    enabled: true
    aliases: [ "message", "m", "tell" ]
    cooldown: 3
    block-system:
      enabled: true
      max-blocks: 50
  nametag:
    enabled: true
    default-visibility: true
    max-length: 16
    allow-colors: false
    update-delay-ticks: 20

# Module Toggles
modules:
  vanish: true
  nick: true
  teleport: true
  gamemode: true
  enchant: true
  enderchest: true
