# =============================================
# EYN Plugin Configuration File
# =============================================

# Global Settings
settings:
  example-setting: true
  player-info:
    mask-ips: true
    show-exact-coords: false
  nametag:
    update-radius: 30
    log-changes: true
    prevent-bypass: true
  messaging:
    cooldown: 3
    socialspy-format: "&7[SPY] &d%sender% &8-> &d%receiver%&7: %message%"
    reply-prefix: "~"
    allow-message-toggling: true

# Discord Settings
discord:
  link: "https://discord.gg/example"  # Replace with your Discord invite link

# Heal Command Settings
heal:
  max_health: 20.0       # Default maximum health (double value)
  food_level: 20         # Food level to set (range 0-20)
  clear_fire: true       # Extinguish players when healed
  clear_effects: true    # Remove potion effects when healed

# Permission Overrides (if applicable)
permissions:
  override:
    eyn.nametag.others: "group.admin"
    eyn.vanish.others: "group.moderator"

# Cooldown Settings (in seconds)
cooldowns:
  clearchat: 3
  enchant: 10
  heal: 30

# Command Configurations
commands:
  msg:
    enabled: true
    aliases: [ "message", "m", "tell" ]
    cooldown: 3
    block-system:
      enabled: true
      max-blocks: 50
  nametag:
    enabled: true
    default-visibility: true
    max-length: 16
    allow-colors: false
    update-delay-ticks: 20

# Message Configurations
messages:
  player_only_command: "&cThis command can only be used by players."
  no_permission: "&cYou do not have permission to do that."

  msg:
    usage: "&cUsage: /msg <player> <message>"
    sent: "&7[You &8-> &7%target%] &f%message%"
    received: "&7[%sender% &8-> &7You] &f%message%"
    blocked: "&cYou cannot message %target%."
    target_not_found: "&cPlayer %target% not found."

  nametag:
    hidden_self: "&7Your nametag is now hidden."
    visible_self: "&aYour nametag is now visible."
    hidden_other: "&7Hidden %player%'s nametag."
    visible_other: "&aShown %player%'s nametag."
    hidden_by: "&7Your nametag was hidden by %player%."
    visible_by: "&aYour nametag was shown by %player%."

  # Module-specific messages
  heal:
    success: "&aYou have been healed!"
    other_success: "&aHealed &e%player%."
    healed_by: "&aYou were healed by &e%player%."

  fly:
    toggled: "&aFlight mode toggled."
  
  back:
    success: "&aTeleported to your previous location!"
  
  god:
    toggled: "&aGod mode toggled."

  gamemode:
    updated: "&aGame mode updated."
  
  weather:
    updated: "&aWeather updated."
  
  durability:
    repaired: "&aItem durability repaired."

  tp:
    success: "&aTeleported successfully."

  warp:
    not_found: "&cWarp &r%warp% &cdoes not exist."
  
  discord:
    message: "&9Join our Discord! &r&nClick here to join!"
    hover: "&7Click to join our Discord server!"

  vanish:
    toggled: "&aVanish mode toggled."

  playtime:
    display: "&aPlaytime: &r%hours% hours, %minutes% minutes."

  playerinfo:
    display: "&aPlayer info: &r%player%."

  online:
    count: "&aOnline players: %count%."

  clearchat:
    success: "&aChat has been cleared by &r%player%."

  mute:
    success: "&aPlayer muted successfully."

  ping:
    response: "&aYour ping is: &r%ping%."

  nick:
    updated: "&aNickname updated successfully."

  enchant:
    success: "&aEnchantment applied: %enchant% %level%."

# Module Toggles
modules:
  vanish: true
  nick: true
  teleport: true
  gamemode: true
  enchant: true
  enderchest: true
