name: EYNPlugin
main: com.example.eynplugin.EYNPlugin
version: "1.0"
api-version: "1.21"

description: "Everything You Need Plugin"
author: "YourName"

# Optional dependency declarations (uncomment if needed)
# depend: [Vault, LuckPerms]
# softdepend: []

commands:
  # Utility and core commands
  utils:
    description: "Utility commands for the EYN Plugin"
    usage: "/<command>"
  fly:
    description: "Toggle flight mode"
    usage: "/<command> [player]"
    aliases: ["flight"]
  back:
    description: "Teleport to last location"
    usage: "/<command>"
  god:
    description: "Toggle invincibility"
    usage: "/<command>"
  gmc:
    description: "Switch to creative mode"
    usage: "/<command>"
  gms:
    description: "Switch to survival mode"
    usage: "/<command>"
  gmsp:
    description: "Switch to spectator mode"
    usage: "/<command>"
  gma:
    description: "Switch to adventure mode"
    usage: "/<command>"
  speed:
    description: "Set your speed"
    usage: "/<command> <speed>"
    permission: "eyn.speed"


  # Weather and item commands
  weather:
    description: "Change the weather"
    usage: "/<command> <rain|thunder|clear|sunny>"
  durability:
    description: "Change the durability of the item in hand"
    usage: "/<command> <value>"

  # Warp commands
  warp:
    description: "Teleport to a warp location"
    usage: "/<command> <name>"
  setwarp:
    description: "Set a new warp location"
    usage: "/<command> <name>"
  delwarp:
    description: "Delete a warp location"
    usage: "/<command> <name>"
  warplist:
    description: "List all available warps"
    usage: "/<command>"
  renamewarp:
    description: "Rename a warp location"
    usage: "/<command> <oldname> <newname>"

  # Communication and social commands
  discord:
    description: "Get the Discord server invite link"
    usage: "/<command>"
    aliases: ["dc"]
  kill:
    description: "Kill yourself or another player"
    usage: "/<command> [player]"
  killall:
    description: "Kill all players on the server"
    usage: "/<command>"

  # Vanish and player information commands
  vanish:
    description: "Toggle vanish mode"
    usage: "/<command> [player]"
    aliases: ["v"]
  vanishlist:
    description: "List all vanished players"
    usage: "/<command>"
    aliases: ["vlist"]
  playtime:
    description: "Check your or another player's playtime"
    usage: "/<command> [player]"
  playerinfo:
    description: "View detailed information about a player"
    usage: "/<command> [player]"
    aliases: ["pinfo", "pi"]
  online:
    description: "View list of online players"
    usage: "/<command>"
    aliases: ["list", "who", "players"]
  clearchat:
    description: "Clear the chat"
    usage: "/<command>"
    aliases: ["cc"]

  # Moderation commands
  mute:
    description: "Mute a player"
    usage: "/<command> <player> <reason>"
  unmute:
    description: "Unmute a player"
    usage: "/<command> <player>"
  ban:
    description: "Ban a player permanently"
    usage: "/<command> <player> <reason>"
  tempban:
    description: "Ban a player temporarily"
    usage: "/<command> <player> <duration> <reason>"
  unban:
    description: "Unban a player"
    usage: "/<command> <player>"
  kick:
    description: "Kick a player from the server"
    usage: "/<command> <player> <reason>"
  ping:
    description: "Check your ping or another player's ping"
    usage: "/<command> [player]"
    aliases: ["latency"]
  nick:
    description: "Change your nickname or another player's nickname"
    usage: "/<command> [player] <nickname|reset>"
    aliases: ["nickname"]

  # Home and XP commands
  home:
    description: "Manage your homes"
    usage: "/home <name> [set|del|rename]"
    aliases: ["sethome", "delhome", "renamehome"]
  xp:
    description: "Manage player experience points"
    usage: "/xp <give|take|set> <amount> [player]"
    aliases: ["exp", "experience"]

  # World and miscellaneous commands
  worldinfo:
    description: "Display information about the current world"
    usage: "/<command>"
    permission: "eyn.worldinfo"
  anvil:
    description: "Opens a virtual anvil"
    usage: "/<command>"
    permission: "eyn.anvil"
  freeze:
    description: "Freeze or unfreeze a player"
    usage: "/<command> <player>"
    permission: "eyn.freeze"
    aliases: ["togglefreeze"]
  tp:
    description: "Teleport to a player"
    usage: "/<command> <player>"
    permission: "eyn.tp"
  tpall:
    description: "Teleport all players to you"
    usage: "/<command>"
    permission: "eyn.tp"
  tphere:
    description: "Teleport a player to you"
    usage: "/<command> <player>"
    permission: "eyn.tp"
  burn:
    description: "Set a player on fire"
    usage: "/<command> <player> [duration]"
    permission: "eyn.burn"
  clearinventory:
    description: "Clear a player's inventory"
    usage: "/<command> [player]"
    permission: "eyn.clearinventory"
    aliases: ["ci", "clearinv"]
  enderchest:
    description: "Open a player's ender chest"
    usage: "/<command> [player]"
    permission: "eyn.enderchest"
    aliases: ["ec", "echest"]

  # Reload and teleport request commands
  eynreload:
    description: "Reload plugin configuration"
    usage: "/<command>"
    permission: "eyn.reload"
    aliases: ["pluginreload", "preload"]
  tpa:
    description: "Send teleport request to a player"
    usage: "/<command> <player>"
    permission: "eyn.tpa"
    aliases: ["teleportrequest"]
  tpaccept:
    description: "Accept a teleport request"
    usage: "/<command>"
    permission: "eyn.tpaccept"
  tpdeny:
    description: "Deny a teleport request"
    usage: "/<command>"
    permission: "eyn.tpaccept"

  # Enchant and heal commands
  enchant:
    description: "Enchants the item in hand with the specified enchantment."
    usage: "/enchant <enchantment> <level> [player]"
    permission: "eyn.enchant"
    permission-message: "&cYou do not have permission to use this command."
  heal:
    description: "Heal yourself or another player"
    usage: "/<command> [player]"
    aliases: ["cure"]
    permission: "eyn.heal"
    permission-message: "&cYou don't have permission to heal players!"
  smithing:
    description: "Opens a virtual smithing table"
    usage: "/<command>"
    permission: "eyn.smithing"
    permission-message: "&cYou don't have permission to use the smithing table!"
    aliases: ["smithingtable"]

  # Economy commands
  pay:
    description: "Send money to another player"
    usage: "/<command> <player> <amount>"
    permission: "eyn.pay"
    permission-message: "&cYou don't have permission to use this command!"
    aliases: ["sendmoney"]
  balance:
    description: "Check your balance or another player's balance"
    usage: "/<command> [player]"
    permission: "eyn.balance"
    permission-message: "&cYou don't have permission to use this command!"
    aliases: ["bal", "money"]

  # New command
  stonecutter:
    description: "Opens a virtual stonecutter"
    usage: "/<command>"
    permission: "eyn.stonecutter"

  effect:
    description: "Apply potion effects to yourself or others"
    usage: "/<command> <player> <effect> <duration> <amplifier> or /effect <effect> <duration> <amplifier>"
    permission: "eyn.effect"

permissions:
  eyn.home:
    description: "Allows using home commands"
    default: true
  eyn.tp:
    description: "Allows using teleport commands"
    default: op
  eyn.burn:
    description: "Allows burning other players"
    default: op
  eyn.home.set:
    description: "Allows setting homes"
    default: true
  eyn.home.delete:
    description: "Allows deleting homes"
    default: true
  eyn.home.rename:
    description: "Allows renaming homes"
    default: true
  eyn.home.teleport:
    description: "Allows teleporting to homes"
    default: true
  eyn.home.unlimited:
    description: "Bypass home limits"
    default: op
  eyn.xp:
    description: "Parent permission for all XP commands"
    default: op
  eyn.xp.give:
    description: "Allows giving XP to players"
    default: op
  eyn.xp.take:
    description: "Allows taking XP from players"
    default: op
  eyn.xp.set:
    description: "Allows setting player XP"
    default: op
  eyn.xp.others:
    description: "Allows modifying other players' XP"
    default: op
  eyn.smithing:
    description: "Allows using the smithing table command"
    default: true
  eyn.pay:
    description: "Allows using the pay command"
    default: true
  eyn.balance:
    description: "Allows checking own balance"
    default: true
  eyn.balance.others:
    description: "Allows checking other players' balances"
    default: op
  eyn.stonecutter:
    description: "Allows using the stonecutter command"
    default: true
  eyn.effect:
    description: "Allows using the effect command on self"
    default: true
  eyn.effect.others:
    description: "Allows using the effect command on others"
    default: op
